### ISSUE TITLE
Input validation missing in time

### ISSUE THREAD

**Issue by hakimcseru** [ARCommunications/wp-scheduled-posts#1]
Please check the input :35. Hour is missing. On can input with
![2018-10-30_14-57-40](https://user-images.githubusercontent.com/6298346/47706908-9af65a80-dc54-11e8-8c13-0276d87e1639.png)
out hour. Not possible.

**Comment by nayanchamp7** [comment]
issue solved!...

**Comment by hakimcseru** [comment]
Solved
